# -*- coding: utf-8 -*-
"""FINAL STUDDY BUDDY!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqLxPhf9jspIo3815IRcXUHy8GTR78_8
"""



# Commented out IPython magic to ensure Python compatibility.

# import streamlit as st
# import google.generativeai as genai
# # Configure Gemini API
# genai.configure(api_key="AQ.Ab8RN6I_uELTu3tU-jw0HOXB6VvR2Rds0Itr8QW22DiH-mXgHg")
# model = genai.GenerativeModel("gemini-2.5-flash")
# st.set_page_config(page_title="AI Learning Buddy Srija", page_icon="🎓")
# st.title("🎓 AI Learning Buddy Srija")
# topic = st.text_input("Enter a Topic")
# option = st.selectbox(
# "Choose Activity",
# [
# "Explain Concept",
# "Real-Life Example",
# "Generate Quiz",
# "Ask Anything"
# ]
# )
# if st.button("Generate"):
# if topic == "":
# st.warning("Please enter a topic.")
# else:
# if option == "Explain Concept":
# prompt = f"Explain {topic} in simple language for a beginner."
# elif option == "Real-Life Example":
# prompt = f"Give one simple real-life example of {topic}."
# elif option == "Generate Quiz":
# prompt = f"Create 5 MCQs on {topic} with answers."
# else:
# prompt = topic
# response = model.generate_content(prompt)
# st.write(response.text)

# Commented out IPython magic to ensure Python compatibility.

# import streamlit as st
# import google.generativeai as genai
# 
# # Configure Gemini API
# genai.configure(api_key="AQ.Ab8RN6I_uELTu3tU-jw0HOXB6VvR2Rds0Itr8QW22DiH-mXgHg")
# model = genai.GenerativeModel("gemini-2.5-flash")
# 
# st.set_page_config(page_title="AI Learning Buddy Srija", page_icon="🎓")
# st.title("🎓 AI Learning Buddy Srija")
# 
# topic = st.text_input("Enter a Topic")
# option = st.selectbox(
#     "Choose Activity",
#     [
#         "Explain Concept",
#         "Real-Life Example",
#         "Generate Quiz",
#         "Ask Anything"
#     ]
# )
# 
# if st.button("Generate"):
#     if topic == "":
#         st.warning("Please enter a topic.")
#     else:
#         if option == "Explain Concept":
#             prompt = f"Explain {topic} in simple language for a beginner."
#         elif option == "Real-Life Example":
#             prompt = f"Give one simple real-life example of {topic}."
#         elif option == "Generate Quiz":
#             prompt = f"Create 5 MCQs on {topic} with answers."
#         else:
#             prompt = topic
# 
#         response = model.generate_content(prompt)
#         st.write(response.text)







# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import google.generativeai as genai
# 
# # Configure Gemini API
# genai.configure(api_key="AQ.Ab8RN6I_uELTu3tU-jw0HOXB6VvR2Rds0Itr8QW22DiH-mXgHg")
# model = genai.GenerativeModel("gemini-2.5-flash")
# 
# st.set_page_config(page_title="AI Learning Buddy Srija", page_icon="🎓")
# st.title("🎓 AI Learning Buddy Srija")
# 
# topic = st.text_input("Enter a Topic")
# option = st.selectbox(
#     "Choose Activity",
#     [
#         "Explain Concept",
#         "Real-Life Example",
#         "Generate Quiz",
#         "Ask Anything"
#     ]
# )
# 
# if st.button("Generate"):
#     if topic == "":
#         st.warning("Please enter a topic.")
#     else:
#         if option == "Explain Concept":
#             prompt = f"Explain {topic} in simple language for a beginner."
#         elif option == "Real-Life Example":
#             prompt = f"Give one simple real-life example of {topic}."
#         elif option == "Generate Quiz":
#             prompt = f"Create 5 MCQs on {topic} with answers."
#         else:
#             prompt = topic
# 
#         response = model.generate_content(prompt)
#         st.write(response.text)



 # Give Streamlit time to start







public_url = ngrok.connect(8501)
print(public_url)
